global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'fastapi-app'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['fastapi_app:8000'] # 'fastapi_app' is the service name in docker-compose